# Generated by Django 4.2.7 on 2025-04-06 21:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='habit_notes_photos/')),
                ('mood', models.CharField(blank=True, choices=[('happy', '😊 Happy'), ('neutral', '😐 Neutral'), ('sad', '😞 Sad'), ('angry', '😠 Angry'), ('tired', '😩 Tired')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='habits.habit')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
