# Generated by Django 4.2.7 on 2025-03-26 21:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of your habit', max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('category', models.CharField(choices=[('Good', 'Good'), ('Bad', 'Bad')], default='Good', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Every 2 Weeks', 'Every 2 Weeks'), ('Monthly', 'Monthly'), ('Every 6 Months', 'Every 6 Months'), ('Yearly', 'Yearly')], default='Daily', max_length=20)),
                ('end_date', models.DateField(help_text='When should this habit end?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_user_habit'),
        ),
    ]
